-- Deploy uniondesk:20240318-initial-migration to pg

BEGIN;

CREATE TABLE translations (
    id uuid primary key,
    lang text,
    content text
);

CREATE TABLE groups (
    id uuid primary key,
    role_id text not null,
    name uuid references translations(id),
    description uuid references translations(id),
    ticket_category_id text not null
);

CREATE TABLE categories (
    id uuid primary key,
    parent uuid references categories(id),
    name uuid references translations(id),
    assignable bool not null
);

CREATE TABLE tickets (
    id uuid primary key,
    ticket_id bigint generated by default as identity,
    id_prefix text not null,
    assigned_group uuid references groups(id),
    assignee text,
    category uuid references categories(id),
    title text
);


CREATE TABLE comments (
    id uuid primary key,
    ticket_id uuid references tickets(id),
    content text not null,
    sender text
);

CREATE TABLE attachments (
    id uuid primary key,
    comment uuid references comments(id),
    hash text not null,
    file_name text not null,
    size bigint
);
COMMIT;
